name: DeployTerraform

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform
          path: ${{ github.workspace }}//appservice
  
  deploy-infra-dev:
    name: Deploy Infra Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/appservice
    
    environment:
      name: dev

    needs: build
    steps:
      - name: Download Terraform
        uses: actions/download-artifact@v3
        with:
          name: terraform
          path: ${{ github.workspace }}//appservice
     